package com.consultora.ligapadel.enums;

public enum Permiso {
    //ADMIN
    ACEPTAR_INSCRIPCION_EQUIPO,
    ACEPTAR_INSCRIPCION_JUGADOR,
    CAMBIAR_NOMBRE_LIGA,
    BORRAR_EQUIPO,
    BORRAR_LIGA,
    BORRAR_INSCRIPCION,
    MODIFICAR_PUNTUACION,
    MODIFICAR_FECHA,
    MODIFICAR_PENALIZACION,
    MODIFICAR_MARCADOR,
    RESOLVER_RECLAMACION,
    APROBAR_ROL,
    CAMBIAR_CAPITAN,

    //CAPITAN
    CREAR_EQUIPO,
    BORRAR_EQUIPO_PROPIO,
    ACEPTAR_INSCRIPCION_JUG_EQUIPO,
    BORRAR_INSCRIPCION_JUG_EQUIPO,
    MODIFICAR_LUGAR,
    INDICAR_MARCADOR_LOCAL,
    MODIFICAR_MARCADOR_LOCAL,
    APROBAR_MARCADOR_VISITANTE,
    RECLAMAR_MARCADOR,
    ANUNCIAR_CONVOCATORIA,
    MODIFICAR_CONVOCATORIA,
    SOLICITAR_CAMBIO_CAPITAN,

    //JUGADOR
    MODIFICAR_INFO_JUGADOR,
    INSCRIBIERSE_EQUIPO,
    APUNTARSE_PARTIDO,
    DESAPUNTARSE_PARTIDO,
    BORRAR_USUARIO_PROPIO,
    BORRAR_INSCRIPCION_PROPIO
}
